### ISSUE TITLE
AutoRaise interferes with Alt-Tab MRU behavior

### ISSUE THREAD

**Issue by samholmes** [sbmpost/AutoRaise#102]
https://user-images.githubusercontent.com/517469/182886056-f00ca093-2db3-4423-b682-cc776740cd00.mp4

The video above illustrates how when using alt-tab to switch between apps, sometimes AutoRaise will cause an incorrect MRU ordering. I suspect the issue with that for a few milliseconds, the cursor is registered under an app while transitioning after Alt-Tab, which causes an incorrect "last active app" to register.

**Comment by sbmpost** [comment]
@samholmes 
It would seem the issue happens at the very end of your screen recording: you are in the terminal, and you switch to the browser. While doing so, the mouse briefly passes the visual code window. So that when you switch back, you end up there instead of the terminal.

It could indeed be the case that AutoRaise is trying to activate visual studio code while transitioning to the browser. But I would have to investigate.

Thanks for reporting this subtle, but nasty bug 🙂

**Comment by sbmpost** [comment]
@samholmes 
I might have a fix. You can check with the UI version if you like, see:
https://github.com/sbmpost/AutoRaise/blob/99-introduce-new-settings/AutoRaise.dmg

**Comment by sbmpost** [comment]
@samholmes 
v3.5 was released.

**Comment by samholmes** [comment]
II pulled master and rebuilt with:

```
make clean && make CXXFLAGS="-DOLD_ACTIVATION_METHOD -DEXPERIMENTAL_FOCUS_FIRST" && make install
```

And now the `mouseStop` in my config is ignored:

```
delay=0
mouseStop=true
warpX=0.5
warpY=0.5
```

**Comment by sbmpost** [comment]
@samholmes 
Setting -delay 2 now gives you the exact same behaviour as mouseStop.
The mouseStop option therefore serves no purpose any longer.

Many new options + a UI was added in the latest release. See also the latest readme
