### ISSUE TITLE
More granular choices in delay for focus and raise

### ISSUE THREAD

**Issue by Zatfer17** [sbmpost/AutoRaise#103]
Hi, would it be possible to add to the GUI more low ms choices to the delay for focus and raise? Something like 0.1, 0.2, 0.4 ms would be perfect. I find myself ok with 0.5ms but sometimes I would prefer to have something in between. Btw awesome job!

**Comment by sbmpost** [comment]
@Zatfer17 
It is possible, but comes with a price because AutoRaise checks for mouse activity every 50ms. If we would reduce this number, then CPU usage goes up. Precious CPU cycles that you probably want to spend on other things ;-)
That being said, I think a toggle might do the trick, something like:

    Poll every: [20 or 50] microseconds
    note: 20 microseconds increases responsiveness, but increases CPU usage.
 
Then if the toggle is set to 20ms, all delays could be in 20ms units instead of 50ms units.

**Comment by sbmpost** [comment]
@Zatfer17 
It took a while the option to set the poll interval (thereby increasing granularity) is now part of this branch:

https://github.com/sbmpost/AutoRaise/tree/add-poll-millis-and-ignore-space-changed-options

The UI part of this is still being worked on. It may take some time to release so bear with me ;-)

**Comment by sbmpost** [comment]
@Zatfer17 
@chrisaj I am about to merge [PR#106](https://github.com/sbmpost/AutoRaise/pull/110). It contains an updated UI which allows you to set the polling interval. This in turn should increase granularity.

**Comment by sbmpost** [comment]
Version 3.7 with updated settings has been released. The ui dmg image was updated accordingly
