### ISSUE TITLE
Add focusedApps option

### ISSUE THREAD

**Issue by wtf403** [sbmpost/AutoRaise#124]
Hi, first of all, thank you for all the incredible work done
I use AutoRaise with the EXPERIMENTAL_FOCUS_FIRST flag and I want individual apps to remain always in focus. For example, the "Security Agent" window when entering a password. Is there a solution for this already?

**Comment by sbmpost** [comment]
@wtf403 
I am not entirely sure what the request is. For example, what would the behavior be if one or more such "focus always" windows are stacked / overlapping each other? Unfortunately there is no such thing as grouping windows. So you can't say: this group of windows has more focus priority than that group of windows. Or are you asking something different perhaps?

**Comment by sbmpost** [comment]
@wtf403 
Thinking more about it, do you mean some kind of "always on top" feature perhaps? If so, then this is probably an attribute for each window individually. Therefore may be hard to implement.

**Comment by wtf403** [comment]
Ok, i realize that is hard to deal with always focus windows. Just want to get rid of this annoying behavior

https://user-images.githubusercontent.com/73958047/217873911-eedb4055-92a7-4c70-ac29-4cba35f81f0d.mov

**Comment by sbmpost** [comment]
@wtf403 the video clarifies a lot, thanks :-). I think this might be easier to solve but I will have to look into it. We basically want to tell AutoRaise to not focus another app if a certain app from a configurable list is currently focused. It might take some time to have this implemented. Thanks for reporting!

**Comment by sbmpost** [comment]
@wtf403 by the way: the window is a modal window. It may therefore be sufficient to detect it as such. Will have to investigate why AutoRaise thinks it isn't a modal window.

**Comment by sbmpost** [comment]
@wtf403 what kind of terminal application are you using btw? When I use the default terminal, the "sudo su" password prompt appears within the terminal itself so I can't reproduce it ATM.

**Comment by wtf403** [comment]
I use iTerm2 with [pam_reattach](https://github.com/fabianishere/pam_reattach). But I have the same problem without it in other applications (for example when exporting passwords from Firefox)

**Comment by sbmpost** [comment]
@wtf403 I will test this combination next week and hopefully find a fix while at it ;-)

**Comment by sbmpost** [comment]
@wtf403 Ok, I actually found some time before next week.
Can you try with this [in between version](https://github.com/sbmpost/AutoRaise/archive/refs/heads/master.zip)

Note that in order to try this out, you will want to disable v3.6 and compile the version from the link above manually. To do so, use:

    make clean && make CXXFLAGS="-DOLD_ACTIVATION_METHOD -DEXPERIMENTAL_FOCUS_FIRST"

And run from a terminal like so:

    ./AutoRaise -delay 0 -focusDelay 1 -verbose 1

If I am not mistaken, the sudo password dialog you showed in the movie should no longer lose focus. To make this work I added a rule that says: "if the currently focused window has no title, do not switch the focus to another window". However, I am not sure if this rule is too generic. If you can test this, that would be great.

**Comment by wtf403** [comment]
@sbmpost Is it just a link to master? I didn't find any changes in the code with my local running AutoRaise version

**Comment by sbmpost** [comment]
@wtf403 
Strange...

Anyways here is a link to the branch:

https://github.com/sbmpost/AutoRaise/tree/fix-collected-issues

**Comment by wtf403** [comment]
@sbmpost So, I tried a few scenarios. Unfortunately, nothing new 😕

**Comment by wtf403** [comment]
@sbmpost So, I tried a few scenarios. Unfortunately, nothing new :confused:

**Comment by sbmpost** [comment]
@wtf403 
I see...

I am having difficulty reproducing the be honest. I figured the password dialog (security agent?) is a window without title, but I can't really get it to show on my machine in the first place. Perhaps if you could be a bit more specific about the scenarios you tested, I can dig further into this issue. Another thing that could help is the verbose log from the command line (enable with -verbose true) while hovering mouse over the security agent window (and maybe also some other windows that in your opinion shouldn't lose focus). I think a possible solution lies with filtering based on the window title. From your video it looked like the security agent had none, but maybe the verbose log says otherwise.

**Comment by wtf403** [comment]
#128 It seems to be working. However, I had to use bundle_id, because untitled windows do not work with some pop-up menus. Also during the debug it seemed to me that some untitled windows also have a hidden title :neutral_face:

**Comment by wtf403** [comment]
I also noticed that without EXPERIMENTAL_FOCUS_FIRST, the focus is not lost when the target window is inside another app boundaries. Is this a bug or a feature?

**Comment by sbmpost** [comment]
@wtf403 

> I also noticed that without EXPERIMENTAL_FOCUS_FIRST, the focus is not lost when the target window is inside another app boundaries. Is this a bug or a feature

This is a feature. Because then you raise instead of focus. And if you move the mouse over the larger window, the smaller window would go underneath and thus become unreachable. With focus only this is not a problem, but there are still cases when you don't want to focus the larger window. In fact this was one of the solutions I thought of in your case. Then again with focus only, you sometimes do want the larger window to focus. Will have a look at #128 asap. Nice that you got it to work for your use case :-)

**Comment by sbmpost** [comment]
@wtf403 
I left some comments in #128
