### ISSUE TITLE
Not Working with Reeder5

### ISSUE THREAD

**Issue by gregoriomenzel** [sbmpost/AutoRaise#164]
The auto raise and focus is not working for Reeder 5.

I'm running Version 4.1.0 on a MBP a1708 OS Ventura 13.6.

P.s.: this app is incredible, I use it to change the per app settings with my XenseLabs Quickeys as a macro pad.

**Comment by sbmpost** [comment]
@gregoriomenzel 

I tried to find myself a demo version but I can only see the paid version. So I can't reproduce this. What you can try however is updating AutoRaise.mm, line 99, adding your application name to list and recompile according to the instructions in the README:

```
static NSArray * mainWindowAppsWithoutTitle = @[@"Photos", @"Calculator", @"Podcasts", @"Stickies Pro", @"Reeder5"];
```

This may, or may not fix it.

**Comment by gregoriomenzel** [comment]
Hi, 

Thanks a bunch for your response!

I'm no programmer, so I'm unsure if I did correctly.

Either way, it did not work.

I appreciate your help!

**Comment by midfm** [comment]
I was having the same problem with Reeder 5 (suddenly, after using it with autoraise for a while with no issues).

Your Update to line 99 of AutoRaise did work, but the name of the app is "Reeder", NOT "Reeder5", so the line must be:

```
static NSArray * mainWindowAppsWithoutTitle = @[@"Photos", @"Calculator", @"Podcasts", @"Stickies Pro", @"Reeder"];
```

Hope that change can be incorporated, so that it finds its way into the homebrew package.

Thanks for AutoRaise!

**Comment by sbmpost** [comment]
@midfm @gregoriomenzel 

The fix for Reeder is in master now.
