### ISSUE TITLE
Conflicts with ScreenRec

### ISSUE THREAD

**Issue by mayurjobanputra** [sbmpost/AutoRaise#173]
I have two monitors on my Mac Mini setup. When I use this app and then attempt to do a screen capture or video recording with screenrec.com (free for mac/windows), the "select an area to record" function in screenrec doesn't work as expected for my second monitor when I have any app window present.

**Comment by sbmpost** [comment]
@mayurjobanputra 

> the "select an area to record" function in screenrec doesn't work as expected for my second monitor when I have any app window present.

In order to say something about this, I will need more information. What exactly isn't working? Note that I can't reproduce this myself because screenrec only works on Apple silicon which I have not. So I will have rely on as many details as you can provide. Maybe a screen recording using QuickTime helps? It might be difficult though as you are trying to screen record a screen recording tool 🤔

**Comment by mayurjobanputra** [comment]
I figured it out. I'm using a mouse focus app on my Mac because the mouse location doesn't automatically indicate which window the OS should give focus too (which it does on Windows). The app is called Autoraise. If you use autoraise, you need to insert a delay in your settings when also using ScreenRec. I found a way to hack my Mac to also use my Microsoft ego keyboard so when I hit the PRTSCN button, ScreenRec capture runs. 

![image](https://github.com/sbmpost/AutoRaise/assets/6332663/85493235-f3fe-4fe4-81b1-307cbf80d04a)

We can close this ticket, but perhaps it will come in handy for anyone searching for answers

keywords: screenrec, dual monitors, macos, apple, mac, bug, can't capture, second monitor
