### ISSUE TITLE
Will not work in many software

### ISSUE THREAD

**Issue by GASgufneg** [sbmpost/AutoRaise#183]
I am using in macos14.1, the current test to have a lot of software will fail, such as photos, Tencent video have no way to get the normal call fee

**Comment by sbmpost** [comment]
@GASgufneg 

Many software is a very generic statement. Maybe you can be a bit more specific? The photos app should work. There is however an exception in the code especially for photos. Could it be that on your system, the Photos app has a different name because of language settings? And about the video app you mention: can you send me a recording demonstrating what is wrong?

**Comment by sbmpost** [comment]
Closing this one as no further feedback received.
