### ISSUE TITLE
ignoreApps=“IntelliJ IDEA” doesn't stop raise

### ISSUE THREAD

**Issue by jsardello** [sbmpost/AutoRaise#192]
https://github.com/sbmpost/AutoRaise/issues/156 suggests that I should be able to add IntelliJ to my ignoreApps config file. I have a ~/.AutoRaise file setup like this.

```
#AutoRaise config file
delay=0
focusDelay=1
ignoreApps=“IntelliJ IDEA”
```

Other config properties work. Any suggestion on what I'm doing wrong with ignoreApps?

**Comment by sbmpost** [comment]
@jsardello 

It took a while to figure out what was going on, but after copy pasting the exact contents you posted above, I could reproduce the problem. It turns out you are using the wrong quote symbols (Looking carefully, you can see they are printed somewhat in italic font). Below is the corrected version that you can also copy paste:

    #AutoRaise config file
    delay=0
    focusDelay=1
    ignoreApps="IntelliJ IDEA"

**Comment by jsardello** [comment]
Wow! Thanks for digging in. I'm new to Mac OS and I naively thought Text Edit was a plain editor like Notepad. Thanks for making this software, huge QoL improvement for me.
