### ISSUE TITLE
Dropdown in Little Snitch is treated as another window

### ISSUE THREAD

**Issue by ParsimoniousImpala** [sbmpost/AutoRaise#204]
Not sure if this is related to [203](https://github.com/sbmpost/AutoRaise/pull/203): I use Little Snitch which shows a floating alert window when an app is trying to connect. The dropdown menu in this window disappears when the mouse is moved away. The same happens with the Cancel button. Running AutoRaise 5.2 on Sonoma (but I've seen this behaviour on previous OS/AutoRaise versions as well).

https://github.com/sbmpost/AutoRaise/assets/148525881/7779b285-c14c-4167-89a8-96dcf653dbde

**Comment by sbmpost** [comment]
@ParsimoniousImpala

This is because the Little Snitch app does not support Accessibility. Turning on verbose log tells you:

    Copy element: no accessibility support

The current behaviour is find the window below the mouse by iterating over all windows and see if the mouse pointer is bounded by any of them. Then the window is activated. This usually works, but for more advanced applications that do not support accessibility, the fallback isn't appropriate. I will be adding an exception in AutoRaise for Little Snitch, so that the fallback won't happen. This means no focus/raise support for this particular app, but I suppose that is still better than the behaviour shown in the video (and in issue #205)

**Comment by sbmpost** [comment]
@ParsimoniousImpala 

Thinking some more about this issue, perhaps adding the bundle id to the stayFocusedBundleIds list may already improve the situation. I will do some tests tomorrow.

**Comment by sbmpost** [comment]
@ParsimoniousImpala 

Can this issue be closed? See the solution above.
