### ISSUE TITLE
Feature request: Mouse follows focus 

### ISSUE THREAD

**Issue by Dimentium** [sbmpost/AutoRaise#3]
Thank you for useful app!

Is it possible to add a new feature?

Description:
Moving cursor to focused window (when switching through hotkey or other way).

At the moment  I use yabai for this behavioir (but 'focus follow mouse' functionality in your app match me better).

**Comment by sbmpost** [comment]
> Moving cursor to focused window (when switching through hotkey or other way).
Not entirely sure what you mean. Mouse cursor or keyboard cursor?

**Comment by sunilvaltix** [comment]
I think what he means is mouse cursor. When cmd+tab is used to switch to app and that app is, let's say, in the right upper corner and mouse is somewhere in lower bottom part, it would be useful to move the mouse cursor to the middle of app I switched to.

**Comment by Dimentium** [comment]
> Not entirely sure what you mean. Mouse cursor or keyboard cursor?

exactly that sunilvaltix describes.
moving mouse cursor to center of window which has been activated through hotkey or cmd+tab.

**Comment by sbmpost** [comment]
@Dimentium @sunilvaltix 
I have added some experimental code that warps the mouse to the center of the activated window. It is experimental because it might trigger in cases where you wouldn't expect it or the other way around. To do this completely right, one would have to keep track of all launched and terminated applications, which is a bit too much for this small project. It may however be 'good enough' like this? https://github.com/sbmpost/AutoRaise/blob/experimental-feature/AutoRaise

**Comment by Dimentium** [comment]
> @Dimentium @sunilvaltix
> I have added some experimental code that warps the mouse to the center of the activated window. It is experimental because it might trigger in cases where you wouldn't expect it or the other way around. To do this completely right, one would have to keep track of all launched and terminated applications, which is a bit too much for this small project. It may however be 'good enough': https://github.com/sbmpost/AutoRaise/blob/experimental-feature/AutoRaise

That's great and exactly that I wanted.
Thank you!
