### ISSUE TITLE
Hey dude mouse follow focus not working

### ISSUE THREAD

**Issue by Parthvsquare** [sbmpost/AutoRaise#5]
> here is
also an option to warp the mouse to the center of the activated window, using the cmd-tab key combination for example.

I did as you told added a folder name in application folder and used chmod 700 AutoRaise, still after cmd+tab cursor did not made it's way int middle. And can you help me in automator i was not able to follow you.also thanks for making this available

**Comment by Parthvsquare** [comment]
can the wrap be customised, fo example in the top part of the app

**Comment by sbmpost** [comment]
@Parthvsquare I see two questions here: 1) cmd+tab not working, and 2) can it be customised? So can I assume that by you asking question nr 2), you got cmd+tab to work after all? I like your idea to make it customisable. Let me think a bit on how that might be done. Perhaps we could do something like: 0.3 0.2 in the AutoRaise.wrap file. That would then indicate 30% from the left, 20% from the top. What do you think?

**Comment by Parthvsquare** [comment]
Yes that will be great. And yes I got it working.

**Comment by sbmpost** [comment]
I have added the feature, you can try it out using this [binary](https://github.com/sbmpost/AutoRaise/blob/make-warp-position-customizable/AutoRaise) or you can compile the binary yourself.
The new feature can be tested in one of the following two ways:

1) ./AutoRaise -delay 2 -warpX 0.5 -warpY 0.1
2) echo "0.5 0.1" > ~/AutoRaise.warp; ./AutoRaise

**Comment by Parthvsquare** [comment]
am i doing something wrong or it's not working for me
![image](https://user-images.githubusercontent.com/26404957/87652780-43728800-c772-11ea-8200-78fe18d6320a.png)
there is what i did
- i reinstalled 
- cd Application/folder 
- chmod chmod 700 AutoRaise
- ./AutoRaise -delay 2 -warpX 0.5 -warpY 0.1
- echo "0.5 0.1" > ~/AutoRaise.warp; ./AutoRaise

**Comment by sbmpost** [comment]
Seems you are running the wrong binary. I can see that because it says
"Started with 20ms delay, warp: true" whereas the new version should say:
"Started with 20ms delay, warpX: 0.5, warpY: 0.1"

What you can do is:
1. download the binary again, following the link I gave earlier.
2. type in the commands as below:
[user@local ~]$ cd Downloads/
[user@local Downloads]$ chmod 700 AutoRaise
[user@local Downloads]$ ./AutoRaise -delay 2 -warpX 0.5 -warpY 0.1

By sbmpost(c) 2020, usage:
AutoRaise -delay <1=20ms> [-warpX <0.5> -warpY <0.5>]
Started with 40 ms delay, warpX: 0.5, warpY: 0.1

**Comment by sbmpost** [comment]
By way, you may want to check that you don't have 2 binaries running at the same time. You can check with "Activity Monitor" application

**Comment by Parthvsquare** [comment]
ya apparently 2 binary where running. Thanks man ✌🏻

**Comment by sbmpost** [comment]
I am closing this issue now because the code has been merged.
