### ISSUE TITLE
Raise when window is maximized

### ISSUE THREAD

**Issue by krisamundson** [sbmpost/AutoRaise#52]
When command-tab is used to switch between a maximized app and a non-maximized app, moving the mouse back over the maximized app does not auto-raise or focus. This behavior is limited to just maximized apps. Maximized application being defined as: the menubar showing and 3 sides of the application touch the sides of the display and the top of the application is touching the bottom of the menubar.

**Comment by sbmpost** [comment]
If you mean a smaller window that is fully contained by a larger window under it, then this by design. There are 2 cases to consider:

1) contained window is from a different app. You may or may not want the larger window to raise over the smaller one. In most cases probably not

2) contained window is from the same app. You do not want the larger window to raise over the smaller one (typically a file open dialog or other type of modal window)

So in most circumstances you do not want to raise the larger window if it contains the smaller one. If you would like to change this behaviour, you can disable / comment out the "contains_window" check where the code sets the "needs_raise" flag.
