### ISSUE TITLE
Renaming files and folders is difficult with AutoRaise turned on

### ISSUE THREAD

**Issue by BenJackGill** [sbmpost/AutoRaise#56]
I'm not sure how to solve this problem, but I have noticed that renaming files and folders is very difficult when AutoRaise is turned on.

I will try describe the reproduction steps as best I can:

1. Open Finder and right-click on a file to rename it.
2. At this point the "right-click menu" will disappear and the file name becomes editable.
3. But because the mouse is now hovering over white folder space AutoRaise focuses on that, causing the file to immediatley stop renaming mode.

This makes it very hard to rename files and folders.

Because of this behaviour it would be great to have a setting that temporaily turns off AutoRaise while renaming files/folders.

**Comment by sbmpost** [comment]
@BenJackGill 

> I'm not sure how to solve this problem

That makes two of us ;-)
However you can tweak a bit the mouse sensitivity so that it takes a couple more pixels before the mouse is considered moved. But note this will affect all window raising. Below are the code lines to tweak (lines #597-#599). You can increase the 0 values to 4 or something like that:

    bool mouseMoved = fabs(mousePoint.x-oldPoint.x) > 0;
    mouseMoved = mouseMoved || fabs(mousePoint.y-oldPoint.y) > 0;
    oldPoint = mousePoint;

**Comment by rr-os** [comment]
Could the right-click event be trapped and initiate a (configurable) timer period within which auto-raise is temporarily disabled?

Since right-clicking is usually to initiate an action within a window, you're conceivably intending to stay in that window long enough to carry out the brief workflow the right-click initiated.

This would also avoid human habit (mine?) of casting the mouse pointer away from where I am editing.

**Comment by sbmpost** [comment]
@BenJackGill @rr-os 
The latest v3.0 introduced a -mouseStop flag. It also introduced experimental focus first. In combination with -delay 0 (no raise, focus only), these settings will improve the file rename issue significantly. Would be great if you guys can try and report back if it works for you.

**Comment by sbmpost** [comment]
@BenJackGill @rr-os 
I am closing this issue as a new version with UI has been released which allows you to make all the tweaks to mitigate this issue. See also: https://github.com/sbmpost/AutoRaise/blob/master/AutoRaise.dmg
