### ISSUE TITLE
When using autohide menu bar on an external monitor, hovering over the menu bar raises the window underneath

### ISSUE THREAD

**Issue by alexclaydon** [sbmpost/AutoRaise#65]
Hello, this is such a great utility.  No "focus-follows-mouse" is always the thing I miss most from Linux.

I noticed that when using the MacOS autohide menu bar setting with an external monitor, hovering over the menu bar (in its revealed state, on top of any windows underneath) raises the window underneath, preventing access to the menu bar.  I wondered if this is a bug; it seems to me as though any window obscured by a visible menu bar should not be raised.

**Comment by sbmpost** [comment]
@alexclaydon 
Thank you for this bug report. I am indeed not entirely sure if this is a bug or something that is easily solvable. I will need some time to test it properly.

**Comment by sbmpost** [comment]
@alexclaydon 
I did some analysis, and this is indeed a difficult problem to solve. The menu bar is an application owned object and as such it is difficult to know whether it is currently hiding or not. Because if it is not hiding, we don't want to raise the windows underneath, but if it is hiding, we do want to raise. The only solution I can currently think of is that if the mouse is within the area where the menubar resides (without knowing if it is currently visible), we don't raise. But that is probably not the solution you are looking for.

**Comment by zi0r** [comment]
I ran into this and this solution would actually work for me.

Alternatively, being able to specify a dead zone of X pixels around the edge of the screen might also be a way to address this (where auto-raise would not happen).

**Comment by alexclaydon** [comment]
Just chiming in (after some months!) to say that this solution would work great for me too!  I still use Auto-Raise all the time for certain workflows.

**Comment by sbmpost** [comment]
@zi0r @alexclaydon 
It is probably going to be an option then. Currently I have no time however to implement it due to personal circumstances. As soon as this situation changes, this issue will be in my list of things to pick up. In the meantime let me think of a quick patch (if possible)...

**Comment by sbmpost** [comment]
@zi0r @alexclaydon 

Assuming you guys use the self compiled version, you might try with the patch below:


    float menuBarHeight = 25
    // float menuBarHeight =
    // NSHeight(screen.frame) - NSHeight(screen.visibleFrame) -
    //(screen.visibleFrame.origin.y - screen.frame.origin.y) - 1;

**Comment by movy** [comment]
Any chance to get this committed to a release package? AutoRaise is a great improvement over native MacOS clumsiness when apps constatly try to steal focus from one another, but if an app has a small window at distance from the menubar, it's nearly impossible to open this app's menu unless the window is moved right under the bar, please see the video below: 


https://user-images.githubusercontent.com/4336560/208229902-699c76c0-4ea6-4719-a376-90abca0782c0.mov

Settings used:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/4336560/208229810-620e949e-a476-40bd-95fd-cb1fb01cd9d2.png">

Seems like the menubar is "transparent" in autohide mode, i.e. autoraise sees an app under the bar and raises its window. Hope it makes sense, I guess this is what this issue is about anyway.

**Comment by sbmpost** [comment]
@movy 
> Any chance to get this committed to a release package?

Are you referring to the patch I suggested? I never really got feedback if it works ;-)

**Comment by movy** [comment]
@sbmpost , yes, the patch seems what I'm looking for to fix this behaviour, but I never had experience with building MacOS binaries, so would be grateful if someone can make a binary with the patch. I will test it and post back :)

**Comment by sbmpost** [comment]
@movy Below you will find a zip with patched AutoRaise dmg.

[AutoRaise-patched.zip](https://github.com/sbmpost/AutoRaise/files/10434018/AutoRaise-patched.zip)

> I will test it and post back :)

Please do :-)

**Comment by movy** [comment]
Thanks! I tried the patched version, unfort. it's the same behaviour -- even with 200-300ms delay whenever I move cursor to unhide the menubar, AutoRaise raises the maximised app underneath the bar (most often Chrome), i.e. same thing as in the video above.

**Comment by sbmpost** [comment]
@movy 
Will have a look asap. Your video is very helpful indeed

**Comment by sbmpost** [comment]
@alexclaydon @zi0r 
So it would seem I finally got this fixed in version 3.7 without having to introduce parameters or hacks which is great :-). This stuff is not in master yet because I am preparing a few other fixes as well. If in the meantime you want to test this, you'll have to compile manually using branch: [fix-collected-issues](https://github.com/sbmpost/AutoRaise/tree/fix-collected-issues)

@movy 
This issue in your video is actually unrelated to the initial bug report. In your case, what you probably want to do, is hold the "CTRL" key while navigating to the menu to temporarily disable AutoRaise. Navigating to the menu if there is another app 'in between' in combination with auto raise/focus has always been an issue on OSX. The best we can do is come up with workarounds: In this case the CTRL key.

**Comment by movy** [comment]
cool, thanks, I did not know about CTRL trick. Now I see it's mentioned at the very bottom of the settings window :)
