### ISSUE TITLE
AutoRaise/AutoFocus on mouse click only?

### ISSUE THREAD

**Issue by Inigo-van-Dijk** [sbmpost/AutoRaise#9]
Hey,

Like many, I'm trying to get autofocus to work on MacOS after coming from a different OS that allowed this. However, I only want it to work on **click**. My only issue is that I sometimes have to double-click to click a button or link in another window.

Would this be possible with your nifty little app? I just want to eliminate the doubleclick, but not autoraise on hover.

Thanks! Kind regards,
Inigo

**Comment by sbmpost** [comment]
Hi Inigo. I never really looked into this, so I am not completely sure. However I think OSX only allows a window to receive mouse events if it is active. So normally, when you do your first click, OSX activates the window for you, and only then subsequent mouse events will be seen by the window. To combine these steps into one, one would have to intercept that first click. But since OSX handles that click itself without letting it through, my tool won't be allowed to intercept it.

**Comment by srcreigh** [comment]
@Inigo-van-Dijk Buy a mouse with some extra buttons. Then program one of the buttons to send the right number of clicks (maybe three if you need one click to focus before the double click). This equipment is pretty cheap these days: https://www.amazon.com/s?k=Mouse+Extra+Buttons&ref=nb_sb_noss_2

**Comment by sbmpost** [comment]
After some time of inactivity, I am closing this issue.

**Comment by gavingt** [comment]
> @Inigo-van-Dijk Buy a mouse with some extra buttons. Then program one of the buttons to send the right number of clicks (maybe three if you need one click to focus before the double click). This equipment is pretty cheap these days: https://www.amazon.com/s?k=Mouse+Extra+Buttons&ref=nb_sb_noss_2

You can just program the mouse to do a Cmd+Left Click, since this automatically performs click-through. That said, I wish there was a way to automatically perform Cmd+Left Click any time we click on a window that doesn't have focus.
